name: snakemake-exam
channels:
  - conda-forge
  - bioconda
dependencies:
  # Snakemake
  - snakemake-minimal >=9.7.1

  # Python and packages
  - python
  - biopython
  - pandas # dataframe

  # SeqKit gc and validation
  - seqkit

  # Quarto web page
  - quarto

  # R and packages used in plot_stats.R and report.qmd
  - r-base
  - r-ggplot2
  - r-ggridges
  - r-ggbeeswarm
  - r-cowplot
  - r-dplyr
  - r-tidyverse
  - r-readr
  - r-pheatmap
  - r-knitr
  - r-rmarkdown

